# B6: $^{13}$C MFA for microbial communities

# Introduction

This notebook reproduces the results obtained by an excel notebook provided by Paul Djkistra (personal communication) and used to obtain the fits to $CO_2$ labeling and the  Carbon Use Efficiency (CUE) results in Hagerty *et al* 2014. The mathematical framework is explained in Djikstra *et al* 2011.

# Setup

First, we need to set the path and environment variable properly:

In [1]:
quantmodelDir = '/users/hgmartin/libraries/quantmodel'

This is the only place where the jQMM library path needs to be set.

In [2]:
%matplotlib inline

import sys, os
pythonPath = quantmodelDir+"/code/core"
if pythonPath not in sys.path:
    sys.path.append(pythonPath)
os.environ["QUANTMODELPATH"] = quantmodelDir

dirFiles = os.environ["QUANTMODELPATH"]+'/data/tests/Hagerty2014/'

Then, let's load all needed python packages:

In [3]:
%matplotlib inline
import unittest, os, sys
from IPython.display import SVG
import ToyaData as TD
import shelve
import enhancedLists, GAMSclasses, FluxModels

And move to a scratch directory (to make things faster):

In [4]:
cd /scratch/hgmartin_scratch/tests

/scratch/hgmartin_scratch/tests


# General functions for input file generation

In this section, we define the functions needed to create the input files for the library.

This first function creates input files for solving the Djikstra problem, which is not a standard $^{13}$C MFA problem:

In [5]:
def DijkstraInputFiles2(transitionsFile1,transitionsFile2,feedAFile,feedBFile,feedCFile,feedDFile,fluxLimitsFile,ratios):
    # Load carbon transitions 
    atomTransitionsA = enhancedLists.AtomTransitionList(transitionsFile1)
    atomTransitionsB = enhancedLists.AtomTransitionList(transitionsFile1)
    atomTransitionsC = enhancedLists.AtomTransitionList(transitionsFile2)
    atomTransitionsD = enhancedLists.AtomTransitionList(transitionsFile2)
    
    # Add both feeds
    ReacNetA = ReactionNetworks.C13ReactionNetwork(atomTransitionsA.getReactionNetwork('E. coli wt5h 13C MFA'))
    ReacNetA.addFeed(feedAFile)
    ReacNetA.loadFluxBounds(fluxLimitsFile,measured=True)
    ReacNetB = ReactionNetworks.C13ReactionNetwork(atomTransitionsB.getReactionNetwork('E. coli wt5h 13C MFA'))
    ReacNetB.addFeed(feedBFile)
    ReacNetC = ReactionNetworks.C13ReactionNetwork(atomTransitionsC.getReactionNetwork('E. coli wt5h 13C MFA'))
    ReacNetC.addFeed(feedCFile)
    ReacNetD = ReactionNetworks.C13ReactionNetwork(atomTransitionsD.getReactionNetwork('E. coli wt5h 13C MFA'))
    ReacNetD.addFeed(feedDFile)
    
    # Obtain input files from first feed
    inputFiles = []
    filesA = ReacNetA.getEMUfiles()
    filesA.extend(ReacNetA.getStoichMetRxn13CFiles())
    filesA.extend(ReacNetA.getSourceLabelFile())
    
    # Obtain source labeling file for second feed (all others are the same)
    filesB = ReacNetB.getSourceLabelFile()
    
    # Obtain source labeling file for third and fourth feed
    filesC = ReacNetC.getSourceLabelFile()
    filesD = ReacNetD.getSourceLabelFile()
    
    # Obtain second emm file and change to EMM2
    emm2files = ReacNetC.getEMUfiles()
    for name,string in emm2files:
        if 'emm_simplified' in name:
            name   = name.replace("emm_simplified","emm_simplified2")
            string = string.replace("EMM","EMM2")
            inputFiles.append((name,string))
            
    # Obtain second set of metabolites
    stoich2files = ReacNetC.getStoichMetRxn13CFiles()
    for name,string in stoich2files:
        if 'StoichNetwork' in name:
            name = name.replace('StoichNetwork','StoichNetwork2')
            string = string.replace("S(","S2(")
            inputFiles.append((name,string))

    # Change source labeling file for first feed 
    for name,string in filesA:
        if 'Source_Labeling' not in name:
            inputFiles.append((name,string))
        else:
            newName = 'Source_LabelingA.txt'
            string = string.replace("f.fx","fA.fx")
            inputFiles.append((newName,string))
    
    # Change source labeling file for others feed
    
    for fileList, tag in zip([filesB,filesC,filesD],['B','C','D']):
        for name,string in fileList:
            if 'Source_Labeling' in name:
                newName = "Source_Labeling"+str(tag)+".txt"
                string = string.replace("f.fx","f"+str(tag)+".fx")
                inputFiles.append((newName,string))
    
    # Extra files that are needed 
    twelveset = ['0','1','2','3','4','5','6','7','8','9','10','11','12']
    mset      =  GAMSclasses.GAMSSet('mset',set(twelveset))
    nset      =  GAMSclasses.GAMSSet('nset',set(twelveset))

    msetfilename = 'mset.txt'
    msetSt = mset.write('toString')
    nsetfilename = 'nset.txt'
    nsetSt = nset.write('toString')

    inputFiles.append((msetfilename,msetSt))
    inputFiles.append((nsetfilename,nsetSt))
    
    # Add glucose and pyruvate ratios
    ratioFile = 'ratios.txt'
    lines = []
    ratioGlc = ratios[0]
    ratioPyr = ratios[1]
    
    lines.append('ratioGlu = '+str(ratioGlc)+';')
    lines.append('ratioPyr = '+str(ratioPyr)+';')        
    
    inputFiles.append((ratioFile,'\n'.join(lines)))
    
    return inputFiles

This function is used to automatically create flux bounds files:

In [6]:
def createFluxBoundsFile(r10s,r14s):
    boundsFile = open('fluxBounds.txt','w')
    boundsFile.write('r10:	'+str(r10s[0])+' [==] '+str(r10s[1])+'\n')
    boundsFile.write('r14:	'+str(r14s[0])+' [==] '+str(r14s[1])+'\n')
    boundsFile.close()

This function finds the CUE (Carbon Use Efficieny) as per equation 12 in Dijkstra *et al* Soil Biology and Biochemistry 2011:

In [7]:
def findCUE(resultsDict):
    CUEfluxes = [5,7,8,10]
    co2Flux = 0
    for key in sorted(resultsDict['Vout'].elements.keys(),key=lambda rname: int(rname[0].replace('r','')) ):
        name = key[0]
        fluxNumber = int(name.replace('r',''))
        if fluxNumber in CUEfluxes:
            co2Flux += resultsDict['Vout'].elements[key]
            
    CUE = (600 - co2Flux)/600
    
    return CUE

This function takes the labeling ratios and does the full calculation to provide the CUE: 

In [8]:
def ratio2CUE(ratios):
    # Get input Files
    createFluxBoundsFile([0,100],[0,100])
    inputFiles = DijkstraInputFiles2(dirFiles+'REACTIONSDijkstraGlu.txt',dirFiles+'REACTIONSDijkstraPyr.txt',
                                     dirFiles+'FEEDgluA.txt',dirFiles+'FEEDgluB.txt',
                                     dirFiles+'FEEDpyrA.txt',dirFiles+'FEEDpyrB.txt',dirFiles+'fluxBounds.txt',
                                     ratios)    
    
    # Create GAMS problem
    GAMSfileName = dirFiles+'Hagerty.gms'   # The gams files contains all the problem formulation as
                                            # per Dijkstra et al 2011
    outputFuncs = { 'fAout':(GAMSclasses.GAMSParameterFromResult,['fAout.txt','fAout']),
                    'fBout':(GAMSclasses.GAMSParameterFromResult,['fBout.txt','fBout']),
                    'fCout':(GAMSclasses.GAMSParameterFromResult,['fCout.txt','fBout']),
                    'fDout':(GAMSclasses.GAMSParameterFromResult,['fDout.txt','fBout']),                
                    'Vout' :(FluxModels.fluxParOut,['Vout.txt','Vout']),
                    'Info' :(FluxModels.infoOut,['OFGenInfo.txt']),                
                        }
    GAMSInputFiles = inputFiles

    GAMSprob       = GAMSclasses.GAMSProblem('Djkistra',GAMSfileName,GAMSInputFiles,outputFuncs,execType='serial')  
    GAMSprob.erase = True
    
    # Solve GAMS problem
    with GAMSprob as prob:
        # Run problem
        prob.run()

        # Check if it is done
        prob.waitTilDone()

        # Collect data
        prob.collect()
        
        # Output data 
        resultsDict = prob.Results 
        
    # Find CUE and rest of output
    CUE = findCUE(resultsDict)
    
    fitRatioGlu = resultsDict['fAout'].elements[('co2_c_1', '1')]/resultsDict['fBout'].elements[('co2_c_1', '1')]
    fitRatioPyr = resultsDict['fCout'].elements[('co2_c_1', '1')]/resultsDict['fDout'].elements[('co2_c_1', '1')]
    OF = resultsDict['Info'].OF
    solve = resultsDict['Info'].solvestat
    model = resultsDict['Info'].modelstat
    
    return CUE, [fitRatioGlu,fitRatioPyr], [OF, solve, model]

# Application to Hagerty *et al* 2014 data

## Create input files

Creating input files:

In [9]:
createFluxBoundsFile([0,100],[0,100])
ratios = [2.48,2.00]

inputFiles = DijkstraInputFiles2(dirFiles+'REACTIONSDijkstraGlu.txt',dirFiles+'REACTIONSDijkstraPyr.txt',
                                 dirFiles+'FEEDgluA.txt',dirFiles+'FEEDgluB.txt',
                                 dirFiles+'FEEDpyrA.txt',dirFiles+'FEEDpyrB.txt',dirFiles+'fluxBounds.txt',
                                 ratios)

## Create GAMS problem

Producing optimization problem in GAMS mode:

In [10]:
GAMSfileName = dirFiles+'Hagerty.gms'
outputFuncs = { 'fAout':(GAMSclasses.GAMSParameterFromResult,['fAout.txt','fAout']),
                'fBout':(GAMSclasses.GAMSParameterFromResult,['fBout.txt','fBout']),
                'fCout':(GAMSclasses.GAMSParameterFromResult,['fCout.txt','fBout']),
                'fDout':(GAMSclasses.GAMSParameterFromResult,['fDout.txt','fBout']),                
                'Vout' :(FluxModels.fluxParOut,['Vout.txt','Vout']),
                'Info' :(FluxModels.infoOut,['OFGenInfo.txt']),                
                        }
GAMSInputFiles = inputFiles

In [11]:
GAMSprob       = GAMSclasses.GAMSProblem('Djkistra',GAMSfileName,GAMSInputFiles,outputFuncs,execType='serial')  
GAMSprob.erase = False

## Solve GAMS problem

In [12]:
with GAMSprob as prob:
    # Run problem
    prob.run()

    # Check if it is done
    prob.waitTilDone()

    # Collect data
    prob.collect()
        
    # Output data 
    resultsDict = prob.Results 

In [13]:
os.getcwd()

'/scratch/hgmartin_scratch/tests'

## Print results

Printing ratio for $co_2$ labeling for conditions A (fully labeled glucose) and B (glucose labeled in first carbon):

In [14]:
print resultsDict['fAout'].elements[('co2_c_1', '1')]/resultsDict['fBout'].elements[('co2_c_1', '1')]

2.47997420827


This matches quite well the input ratio of 2.48 contained in the excel sheet provided by Prof. Djkistra. 

Printing ratio for $co_2$ labeling for conditions C (pyruvate labeled in first carbon) and D (pyruvate labeled in second and third carbons):

In [15]:
print resultsDict['fCout'].elements[('co2_c_1', '1')]/resultsDict['fDout'].elements[('co2_c_1', '1')]

2.0000300003


Again matching very well the ratio of 2.00 in the excel sheet solution.

Values of the objective function (0.0 for perfect fit) and the status of solver (should be 1) and model (should be 2): 

In [16]:
print resultsDict['Info'].OF
print resultsDict['Info'].solvestat
print resultsDict['Info'].modelstat

0.0
1.0
2.0


The 0.0 value of the objective function is expected given the good fits to the $co_2$ labeling.

Printing all fluxes for optimal solution:

In [17]:
for key in sorted(resultsDict['Vout'].elements.keys(),key=lambda rname: int(rname[0].replace('r','')) ):
    name = key[0]
    print name+': '+ str(resultsDict['Vout'].elements[key])

r1: 100.0
r2: 2.85199235331
r3: 117.269473384
r4: 125.710845553
r5: 74.5108455533
r6: 46.4108455533
r7: 46.4108455533
r8: 35.7108455533
r9: 26.5
r10: 95.124116508
r11: 84.724116508
r12: 56.4827443387
r13: 28.2413721693
r14: 2.02389113871
r15: 0.7
r16: 19.8
r17: 24.7
r18: 28.1
r19: 10.7
r20: 15.8
r21: 10.4


This values are quite close to the fluxes in the excel sheet. There are small differences probably because of the difference in the solver.

Using findCUE function to get CUE automatically from the results:

In [18]:
print findCUE(resultsDict)

0.580405578054


Again, very close to the value of 0.61 reported in the excel sheet. The difference is due to a few differences in the fluxes probably due to the different solvers used in the excel sheet and GAMS.

# References

Hagerty, Shannon B., et al. "Accelerated microbial turnover but constant growth efficiency with warming in soil." Nature Climate Change 4.10 (2014): 903-906.

Dijkstra, Paul, et al. "Modeling soil metabolic processes using isotopologue pairs of position-specific 13 C-labeled glucose and pyruvate." Soil Biology and Biochemistry 43.9 (2011): 1848-1857.